version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    container_name: upload-videos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upload-videos
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data